### ISSUE TITLE
how to start GeditSchemer?

### ISSUE THREAD

**Issue by linuxbastler** [jonocodes/GeditSchemer#4]
I'm using gedit 3.22.1 on ubuntu with cinnamon.
I installed GeditSchemer and activated the plugin in the settings of gedit.
So far all seems ok.
But I'm too dumb to find how to start GeditSchemer.
gedit 3.22.1 has no menue or button to start GeditSchemer.
What am I missing?

**Comment by jonocodes** [comment]
I'm no longer maitaining this really. But i'm my gnome 3.28 install when I click on the system menu for gedit it shows 'Color Scheme Editor' below the 'Preferences' button.

**Comment by ddnexus** [comment]
Ubuntu 18.04, the menu doesn't appear as you indicated.

**Comment by jonocodes** [comment]
Just did a fresh install of ubuntu 18 and installed 'gedit-plugin-color-schemer' and had not problems. @ddnexus how did you install it?

**Comment by ddnexus** [comment]
Copied the `schemer.plugin` and `shemer` dir into `~/.local/share/gedit/plugins`, selected the plugin in the preferences and restarted gedit. No menu under `Preferences`

**Comment by jonocodes** [comment]
Do you have the same problem if you install it from apt?

**Comment by ddnexus** [comment]
It worked! I think the problem was the missing gedit-plugins-common that has been installed with the apt version. 

You should add a line in the README to tell people that there is a package for it. The current doc is totally misguiding, plus what is written there doesn't work :)
